const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {readFile}=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/tmp/xparty-chrome/chrome-linux64/chrome',args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:390,height:844}});await page.addInitScript(()=>{localStorage.setItem('xparty-consent',JSON.stringify({essential:true,preferences:false}));});
 await page.route('**/api/accounts/config',r=>r.fulfill({json:{enabled:true,url:'https://example.supabase.co',publicKey:'test-public',phoneEnabled:true}}));
 await page.route('https://esm.sh/**',r=>r.fulfill({contentType:'application/javascript',body:`export function createClient(){window.authRequests=[];return {auth:{onAuthStateChange(){},getSession:async()=>({data:{session:null}}),signInWithOtp:async x=>{window.authRequests.push(x);return {data:{}}},verifyOtp:async x=>{window.lastVerification=x;return {data:{}}}}}}`}));
 const assets=path.resolve(__dirname,'../app/src/main/assets/client');await page.route('http://127.0.0.1:8787/**',async r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/api/'))return r.fallback();const name=u.pathname==='/'?'index.html':u.pathname.slice(1);if(!/^[\w-]+\.(js|css|html|svg)$/.test(name))return r.continue();await r.fulfill({body:await readFile(path.join(assets,name)),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':'text/html'});});
 await page.goto('http://127.0.0.1:8787/');await page.click('#welcome-signin');await page.waitForSelector('#account-dialog[data-provider=ready]');await page.fill('#auth-address','person@example.com');await page.check('#privacy-consent');await page.click('#send-otp');await page.waitForFunction(()=>window.authRequests.length===1);assert.equal(await page.evaluate(()=>authRequests[0].options.shouldCreateUser),false);
 await page.fill('#auth-address','changed@example.com');await page.fill('#otp-code','123456');await page.click('#verify-otp');await page.waitForFunction(()=>window.lastVerification);assert.equal(await page.evaluate(()=>lastVerification.email),'person@example.com');
 await page.click('.auth-tabs [data-auth-mode=signup]');await page.click('#send-otp');await page.waitForFunction(()=>window.authRequests.length===2);assert.equal(await page.evaluate(()=>authRequests[1].options.shouldCreateUser),true);
 await page.locator('#auth-method + .internal-select .select-trigger').click();await page.getByRole('option',{name:'Phone OTP',exact:true}).click();await page.fill('#auth-address','123');await page.click('#send-otp');assert.equal(await page.evaluate(()=>authRequests.length),2);await page.fill('#auth-address','+919876543210');await page.click('#send-otp');await page.waitForFunction(()=>authRequests.length===3);assert.equal(await page.evaluate(()=>authRequests[2].phone),'+919876543210');console.log('PASS mocked provider: separate sign-in/sign-up, verification binds original address, invalid phone blocked');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
