const {chromium}=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {readFile}=require('node:fs/promises');const path=require('node:path');const assert=require('node:assert/strict');
const assets=path.resolve(__dirname,'../app/src/main/assets/client');
const fakeYT=`window.YT={Player:class{constructor(id,o){this.o=o;this.s=-1;this.pos=0;this.at=Date.now();const el=document.getElementById(id);this.el=document.createElement('iframe');this.el.id=id;el.replaceWith(this.el);window.fakePlayer=this;setTimeout(()=>o.events.onReady(),20);}cueVideoById(id){this.id=id;this.s=5;this.pos=0;}loadVideoById(v){this.id=v.videoId;this.pos=v.startSeconds||0;this.playVideo();}getIframe(){return this.el;}getPlayerState(){return this.s;}getCurrentTime(){return this.pos+(this.s===1?(Date.now()-this.at)/1000:0);}getDuration(){return 300;}playVideo(){if(this.s!==1){this.s=1;this.at=Date.now();this.o.events.onStateChange({data:1});}}pauseVideo(){this.pos=this.getCurrentTime();this.s=2;this.o.events.onStateChange({data:2});}seekTo(v){this.pos=v;this.at=Date.now();}stopVideo(){this.s=0;this.pos=0;}unMute(){}mute(){}setVolume(){}loadModule(){}unloadModule(){}setOption(){}getOptions(){return []}}};window.onYouTubeIframeAPIReady();`;
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/tmp/xparty-chrome/chrome-linux64/chrome',args:['--no-sandbox','--disable-features=LocalNetworkAccessChecks,LocalNetworkAccessChecksWebSockets','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const errors=[];
async function page(width){const ctx=await browser.newContext({viewport:{width,height:844},hasTouch:true,permissions:['camera','microphone']});const p=await ctx.newPage();p.on('console',m=>{if(m.type()==='error')console.log('BROWSER',m.text())});p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});await p.addInitScript(()=>{const PC=window.RTCPeerConnection;window.RTCPeerConnection=class extends PC{constructor(...a){super(...a);(window.testPeers??=[]).push(this);}};localStorage.setItem('xparty-room-guide-v1','shown');localStorage.setItem('xparty-consent',JSON.stringify({essential:true,preferences:false}));sessionStorage.setItem('xparty-nickname',JSON.stringify({without:true,name:''}));localStorage.setItem('xparty-agreement',JSON.stringify({version:'2026-09-29-v1',acceptedAt:Date.now()}));});
await p.route('https://www.youtube.com/iframe_api',r=>r.fulfill({contentType:'application/javascript',body:fakeYT}));
await p.route('http://127.0.0.1:8787/**',async r=>{const u=new URL(r.request().url());if(u.pathname.startsWith('/api/search'))return r.fulfill({json:{items:[{id:'abcdefghijk',title:'Test video one',duration:'5:00'},{id:'zyxwvutsrqp',title:'Test video two',duration:'5:00'}]}});const name=u.pathname==='/'?'index.html':u.pathname.split('/').pop();if(!/^[\w-]+\.(js|css|html|svg)$/.test(name))return r.continue();try{return r.fulfill({body:await readFile(path.join(assets,name)),contentType:name.endsWith('.js')?'application/javascript':name.endsWith('.css')?'text/css':name.endsWith('.svg')?'image/svg+xml':'text/html'});}catch{return r.continue();}});
await p.goto('http://127.0.0.1:8787/');await p.waitForSelector('#welcome-screen:not([hidden])');await p.screenshot({path:'/tmp/xparty-welcome.png',fullPage:true});await p.click('#welcome-signup');assert.equal(await p.locator('#account-dialog').getAttribute('data-auth-mode'),'signup');await p.screenshot({path:'/tmp/xparty-signup.png',fullPage:true});await p.click('[data-auth-mode=signin]');assert.equal(await p.locator('#account-dialog').getAttribute('data-auth-mode'),'signin');await p.click('#account-guest');await p.waitForSelector('#welcome-screen[hidden]',{state:'attached'});await p.screenshot({path:'/tmp/xparty-home.png',fullPage:true});return p;}
try{const a=await page(390),b=await page(360);await a.click('#create-toggle');await a.waitForSelector('#room:not([hidden])');const code=await a.locator('#room-code').textContent();await b.fill('#code',code);await b.click('#join-button');await b.waitForSelector('#room:not([hidden])');
await a.screenshot({path:'/tmp/mobile-watch.png',fullPage:true});
await a.click('#mobile-nav [data-screen=browse]');await a.fill('#youtube-input','test');await a.locator('#search-results .primary').first().click();await a.waitForFunction(()=>window.fakePlayer?.getPlayerState()===1);await b.waitForFunction(()=>window.fakePlayer?.getPlayerState()===1);console.log('PASS host Play now starts both mock players without second click');
await b.click('#mobile-nav [data-screen=browse]');await b.fill('#youtube-input','test');await b.locator('#search-results .primary').nth(1).click();await a.click('#mobile-nav [data-screen=chat]');await a.getByRole('button',{name:'Accept request',exact:true}).last().click();await a.waitForFunction(()=>window.fakePlayer?.id==='zyxwvutsrqp'&&window.fakePlayer.getPlayerState()===1);await b.waitForFunction(()=>window.fakePlayer?.id==='zyxwvutsrqp'&&window.fakePlayer.getPlayerState()===1);assert.equal(await a.locator('.approval-card .request-actions').count(),0);console.log('PASS approved source starts and pending buttons disappear');
for(const p of[a,b]){await p.click('#mobile-nav [data-screen=call]');await p.click('#mic');}
await a.click('#camera');await b.click('#camera');await a.click('#mobile-nav [data-screen=chat]');await a.getByRole('button',{name:'Accept request',exact:true}).last().click();await b.click('#camera');await a.click('#mobile-nav [data-screen=call]');
for(const p of[a,b])await p.waitForFunction(async()=>{const reports=await Promise.all((window.testPeers||[]).map(pc=>pc.getStats()));return reports.some(r=>[...r.values()].some(x=>x.type==='inbound-rtp'&&x.kind==='audio'&&x.bytesReceived>0));});console.log('PASS synthetic two-client incoming call audio');
for(let i=0;i<3;i++){for(const [dx,expected]of[[-140,'chat'],[140,'call']]){await a.locator('.together-column').evaluate((el,dx)=>{const t=(x)=>new Touch({identifier:1,target:el,clientX:x,clientY:400});el.dispatchEvent(new TouchEvent('touchstart',{bubbles:true,touches:[t(180)]}));el.dispatchEvent(new TouchEvent('touchend',{bubbles:true,changedTouches:[t(180+dx)]}));},dx);assert.equal(await a.locator('body').getAttribute('data-mobile-screen'),expected);}}
assert.equal(await a.locator('#mic').getAttribute('aria-pressed'),'true');console.log('PASS repeated Call/Chat swipes preserve microphone');
for(const screen of ['watch','call','chat','browse']){await a.click('#mobile-nav [data-screen='+screen+']');assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),screen+' overflow');await a.screenshot({path:'/tmp/mobile-'+screen+'.png',fullPage:true,animations:'disabled'});}
await a.click('#mobile-lounge');assert.equal(await a.locator('#mobile-lounge').getAttribute('aria-pressed'),'true');assert((await a.locator('#watch-stage').boundingBox()).height>=200);await a.click('#mobile-guide');assert(await a.locator('#mobile-guide-dialog').isVisible());assert.equal(await a.locator('#mobile-guide-dialog .mobile-update').getAttribute('href'),'xparty-native://update');
await a.locator('#mobile-guide-dialog button').click();await a.click('#mobile-nav [data-screen=browse]');await a.route('**/api/search?q=slow',async r=>{await new Promise(resolve=>setTimeout(resolve,14000));try{await r.fulfill({json:{items:[]}})}catch{}});await a.fill('#youtube-input','slow');await a.waitForFunction(()=>document.querySelector('#search-status').textContent.includes('timed out'),{},{timeout:16000});assert.equal(await a.locator('#search-results').getAttribute('aria-busy'),'false');console.log('PASS timed-out search clears busy state');for(const width of [320,768,1024]){await a.setViewportSize({width,height:844});assert(await a.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'overflow at '+width);}console.log('PASS 320/768/1024 widths');assert.deepEqual(errors,[]);console.log('PASS compact modes, guide, update link, no JS errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
