const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const errors=[];
async function ready(page){page.on('pageerror',e=>errors.push(e.message));await page.addInitScript(()=>{const Original=window.RTCPeerConnection;window.RTCPeerConnection=class extends Original{constructor(...a){super(...a);(window.testPeers??=[]).push(this);}};localStorage.setItem('xparty-consent',JSON.stringify({essential:true,preferences:false}));sessionStorage.setItem('xparty-nickname',JSON.stringify({without:true,name:''}));localStorage.setItem('xparty-agreement',JSON.stringify({version:'2026-09-29-v1',acceptedAt:Date.now()}));});await page.goto('http://localhost:8787/');}
async function callControls(p){if(await p.locator('.call-panel').evaluate(e=>e.classList.contains('call-controls-hidden')))await p.click('#call-controls-toggle');}
async function playbackControls(p){if(await p.locator('#player-shell').evaluate(e=>e.classList.contains('controls-hidden')))await p.click('#controls-toggle');}
try{const a=await browser.newPage({viewport:{width:1366,height:900}}),b=await browser.newPage({viewport:{width:390,height:844}});await ready(a);await ready(b);assert.equal(await a.locator('#capacity').getAttribute('type'),'hidden');await a.click('#nickname-toggle');await a.fill('#nickname-input','Host');await a.click('#nickname-use');await a.click('#create-toggle');await a.waitForSelector('#room:not([hidden])');const code=await a.locator('#room-code').textContent();await b.fill('#code',code);await b.click('#join-button');await b.waitForSelector('#room:not([hidden])');assert.equal(await a.locator('#people-count').textContent(),'2/2');
for(const page of[a,b]){const before=await page.locator('.topbar').boundingBox();await page.click('#people-button');assert(await page.locator('#participants-drawer').isVisible());const after=await page.locator('.topbar').boundingBox();assert.equal(after.height,before.height);const drawer=await page.locator('#participants-drawer').boundingBox();assert(drawer.width<=300);await page.screenshot({path:page===a?'/tmp/xparty-compact-drawer-desktop.png':'/tmp/xparty-compact-drawer-mobile.png'});await page.click('#close-participants');}
await a.click('#nav-settings');await a.locator('.settings-section>summary').filter({hasText:'Appearance'}).click();await a.locator('.settings-section>summary').filter({hasText:'Call audio'}).click();await a.waitForFunction(()=>document.querySelectorAll('.settings-section[open]').length===1);assert.equal(await a.locator('.settings-section[open]').count(),1);await a.locator('#settings-dialog .close-dialog').click();
await callControls(b);await b.click('#camera');await a.click('#panel-chat');await a.waitForSelector('.approval-card');await a.getByRole('button',{name:'Accept request',exact:true}).last().click();await callControls(b);await b.click('#camera');await a.click('#panel-both');await callControls(a);await a.click('#camera');await callControls(a);await a.click('#mic');await callControls(b);await b.click('#mic');await a.waitForFunction(()=>[...document.querySelectorAll('#participants video')].every(v=>v.videoWidth>0));for(const page of[a,b])await page.waitForFunction(async()=>{const reports=await Promise.all((window.testPeers||[]).map(p=>p.getStats()));return reports.some(r=>[...r.values()].some(s=>s.type==='inbound-rtp'&&s.kind==='audio'&&s.bytesReceived>0));});assert.equal(await a.locator('audio').count(),1);assert.equal(await b.locator('audio').count(),1);console.log('PASS decoded synthetic video and incoming audio packets in both directions');
for(const page of[a,b]){const remote=await page.locator('.participant:not(.self)').boundingBox(),self=await page.locator('.participant.self').boundingBox();assert(Math.abs(remote.width/remote.height-.75)<.03);assert(Math.abs(self.width/self.height-.75)<.03);assert(self.x<remote.x+remote.width/2);assert(self.y>remote.y+remote.height/2);}
await b.click('#focus-call');await b.locator('#controls-toggle').click();await b.locator('#pip-handle').focus();await b.keyboard.press('ArrowLeft');await b.locator('#pip-resize').focus();await b.keyboard.press('ArrowRight');assert(await b.locator('#back10').isVisible()===false); // host-only seek remains hidden for approval guests
await b.screenshot({path:'/tmp/xparty-compact-focus-mobile.png'});
await b.click('#nav-home');assert(await b.locator('#create-toggle').isVisible());assert(await b.locator('#join-form').isVisible());const old=await a.locator('#room-code').textContent();await b.fill('#code','ZZZZZZZ');await b.evaluate(()=>document.querySelector('#join-button').disabled=false);await b.click('#join-button');await b.waitForTimeout(300);await b.click('#nav-settings');await b.locator('#settings-dialog summary').filter({hasText:'Notifications'}).first().click();await b.click('#nav-notifications');await b.click('#notification-return');assert.equal(await b.locator('#room-code').textContent(),old);await b.click('#nav-home');await b.click('#create-toggle');await b.waitForFunction(code=>document.querySelector('#room-code').textContent!==code,old);assert.equal(await b.locator('#people-count').textContent(),'1/2');await a.waitForFunction(()=>document.querySelector('#people-count').textContent==='1/2');
await a.click('#nav-home');await a.fill('#code',await b.locator('#room-code').textContent());await a.click('#join-button');await a.waitForSelector('#room:not([hidden])');
await b.locator('#chat-file').setInputFiles({name:'sample.gif',mimeType:'image/gif',buffer:Buffer.from('GIF89a'+'tiny-fixture')});await b.waitForFunction(()=>document.querySelector('#attachment-status').textContent.startsWith('Shared'));await a.click('#panel-chat');await a.waitForSelector('.attachment-card');await a.waitForSelector('.attachment-card img');
for(const width of[320,390,844,1366]){await b.setViewportSize({width,height:width===844?390:900});for(const mode of['default','movie','call']){await playbackControls(b);await b.click('#theater');await b.click('#control-key');await b.locator('[data-watch-view='+mode+']').click();assert.equal(await b.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await b.click('#exit-theatre');}await b.screenshot({path:'/tmp/xparty-compact-'+width+'.png'});}
assert.deepEqual(errors,[]);console.log('PASS compact drawers, accordions, portrait call/self placement, room switching, GIF sharing, responsive theatre, no browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
