const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const errors=[];try{
 const host=await browser.newPage({viewport:{width:1366,height:900}}),context=await browser.newContext({viewport:{width:390,height:844}});let guest=await context.newPage();for(const p of[host,guest])await p.addInitScript(()=>new MutationObserver(()=>{const n=document.querySelector('#nickname-skip');if(n)n.click();const c=document.querySelector('#agree-rules');if(c){c.checked=true;c.dispatchEvent(new Event('change'));document.querySelector('#agree-continue').click();}}).observe(document,{childList:true,subtree:true}));for(const p of[host,guest])p.on('pageerror',e=>errors.push(e.message));
 await host.goto('http://localhost:8787/');await host.getByRole('button',{name:'Accept',exact:true}).click();await host.click('#create-toggle');await host.waitForSelector('#room:not([hidden])');const code=await host.locator('#room-code').textContent();
 await guest.goto('http://localhost:8787/health');await guest.goto('http://localhost:8787/');await guest.getByRole('button',{name:'Accept',exact:true}).click();await guest.fill('#code',code);await guest.click('#join-button');await guest.waitForSelector('#room:not([hidden])');const identity=await guest.evaluate(()=>JSON.parse(localStorage.getItem('xparty-session-v2')).id);
 await guest.goBack();await guest.goForward();if(await guest.locator('#resume-saved').isVisible())await guest.click('#resume-saved');await guest.waitForSelector('#room:not([hidden])');assert.equal(await guest.evaluate(()=>JSON.parse(localStorage.getItem('xparty-session-v2')).id),identity);assert.equal(await host.locator('#people-count').textContent(),'2/2');
 await guest.close();guest=await context.newPage();await guest.addInitScript(()=>new MutationObserver(()=>{const n=document.querySelector('#nickname-skip');if(n)n.click();const c=document.querySelector('#agree-rules');if(c){c.checked=true;c.dispatchEvent(new Event('change'));document.querySelector('#agree-continue').click();}}).observe(document,{childList:true,subtree:true}));guest.on('pageerror',e=>errors.push(e.message));await guest.goto('http://localhost:8787/');await guest.waitForSelector('#active-room-banner:not([hidden])');await guest.fill('#code',code);await guest.click('#join-button');await guest.waitForSelector('#room:not([hidden])');assert.equal(await guest.evaluate(()=>JSON.parse(localStorage.getItem('xparty-session-v2')).id),identity);console.log('PASS browser Back/Forward and new-tab code entry reuse the reserved identity in a full room');
 await host.locator('#room-menu>summary').click();await host.locator('[data-party-mode=HOST_ONLY]').click();await guest.waitForFunction(()=>document.querySelector('#seek').disabled);await host.locator('[data-party-mode=SHARED_CONTROL]').click();await guest.waitForFunction(()=>!document.querySelector('#seek').disabled);await host.locator('#room-menu>summary').click();console.log('PASS live host mode switch updates guest permissions');
 await guest.click('#rename');await guest.fill('#rename-input','My guest');await guest.click('#save-name');await host.locator('.person-label>span').filter({hasText:'My guest'}).waitFor();await host.click('#camera');await guest.waitForFunction(()=>document.querySelector('#participants').dataset.active!=='0');await guest.click('#focus-call');assert.equal(await guest.locator('.chat-panel').isVisible(),false);assert.equal(await guest.locator('.call-panel').isVisible(),true);assert.equal(await guest.locator('.watch-column').evaluate(el=>getComputedStyle(el).position),'fixed');assert.equal(await guest.locator('#room-code').isVisible(),true);const bounds=await guest.locator('.player-bar button').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>e.getBoundingClientRect().right));assert.ok(bounds.every(r=>r<=390));
 await guest.locator('#call-resizer').focus();await guest.keyboard.press('ArrowUp');assert.equal(await guest.locator('#call-resizer').getAttribute('aria-valuenow'),'440');assert.equal(await guest.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await guest.screenshot({path:'/tmp/xparty-v6-focus-mobile.png',fullPage:true});await host.click('#focus-call');await host.screenshot({path:'/tmp/xparty-v6-focus-desktop.png',fullPage:true});console.log('PASS focused call, floating movie, accessible resize, nickname, and mobile containment');
 assert.deepEqual(errors,[]);assert.equal(await host.locator('#end-room').count(),0);await guest.locator('#room-menu>summary').click();await guest.click('#leave');await guest.waitForSelector('#lobby:not([hidden])');assert.equal(await guest.evaluate(()=>localStorage.getItem('xparty-session-v2')),null);console.log('PASS self-exit cleanup; no end-room action');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
