const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const {createXparty}=await import('../server.mjs');process.env.ALLOWED_ORIGINS='http://127.0.0.1:8793';const app=createXparty();await new Promise(r=>app.server.listen(8793,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port;
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-gpu','--disable-software-rasterizer','--disable-features=WebRtcHideLocalIpsWithMdns','--autoplay-policy=no-user-gesture-required','--allow-loopback-in-peer-connection','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const errors=[];
 try{
 const a=await browser.newPage({viewport:{width:1366,height:900}}),b=await browser.newPage({viewport:{width:390,height:844}});
 for(const [i,p]of[a,b].entries()){
 p.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});await p.addInitScript(name=>{window.__pcs=[];const Real=RTCPeerConnection;window.RTCPeerConnection=new Proxy(Real,{construct(Target,args){const pc=new Target(...args);window.__pcs.push(pc);pc.__candidates=[];pc.addEventListener('icecandidate',e=>{if(e.candidate)pc.__candidates.push(e.candidate.candidate)});return pc}});localStorage.setItem('xparty-consent',JSON.stringify({essential:true,preferences:true,analytics:false}));localStorage.setItem('xparty-agreement',JSON.stringify({version:'2026-09-29-v1'}));localStorage.setItem('xparty-nickname',JSON.stringify({without:false,name}));},i?'Guest':'Host');
 await p.route('https://www.youtube.com/iframe_api',r=>r.fulfill({contentType:'text/javascript',body:`window.YT={Player:class{constructor(id,o){this.options=o;this.position=0;this.state=2;this.seeks=0;window.fakeYT=this;setTimeout(()=>o.events.onReady({target:this}),0);setInterval(()=>{if(this.state===1)this.position+=.1},100);}cueVideoById(id){this.id=id;this.position=0;this.state=2;}unMute(){}setVolume(n){this.volume=n;}stopVideo(){this.state=2;}getCurrentTime(){return this.position;}getDuration(){return 180;}getPlayerState(){return this.state;}seekTo(n){this.position=n;this.seeks++;}playVideo(){this.state=1;this.options.events.onStateChange({data:1});}pauseVideo(){this.state=2;this.options.events.onStateChange({data:2});}}};window.onYouTubeIframeAPIReady();`}));
 await p.goto(base);
 }
 await a.click('#create-toggle');await a.screenshot({path:'/tmp/xparty-create-debug.png'});console.log('CREATE',await a.locator('#toast').textContent(),await a.locator('dialog[open]').count());await a.waitForSelector('#room:not([hidden])');const code=await a.locator('#room-code').textContent();await b.fill('#code',code);await b.click('#join-button');await b.waitForSelector('#room:not([hidden])');await a.waitForFunction(()=>document.querySelector('#people-count').textContent==='2/2');
 assert.equal(await a.locator('#nickname-dialog').count(),0);assert.equal(await a.locator('.host-crown').count(),1);assert.equal(await a.locator('.media-status').count(),2);await b.click('#panel-chat');await b.fill('#message-input','Hello host');await b.locator('#chat-form button[type=submit]').click();await a.getByText('Hello host',{exact:true}).waitFor();await b.click('#panel-both');
 await a.locator('#control-key').click();await a.getByRole('button',{name:'Room settings',exact:true}).click();await a.locator('#capacity-options input').fill('4');await a.locator('#room-theme + .internal-select .select-trigger').click();await a.locator('#room-theme + .internal-select').getByRole('option',{name:'Royal Violet',exact:true}).click();await a.click('#save-room-settings');await b.waitForFunction(()=>document.querySelector('#people-count').textContent==='2/4'&&document.documentElement.dataset.theme==='violet');
 await a.click('#nav-settings');await a.locator('#settings-dialog summary').filter({hasText:'Sound'}).click();await a.uncheck('#notification-master');await a.locator('#notification-volume').fill('20');await a.locator('#display-toggle').evaluate(s=>s.checked=false);await a.locator('#language-select').evaluate(s=>s.value='hi');await a.locator('#theatre-fit').evaluate(s=>s.value='cover');await a.click('#save-settings');assert.equal(await a.evaluate(()=>document.documentElement.lang),'hi');assert.equal(await a.evaluate(()=>document.documentElement.dataset.display),'light');await a.click('#nav-settings');await a.locator('#language-select').evaluate(s=>s.value='en');await a.locator('#display-toggle').evaluate(s=>s.checked=true);await a.click('#save-settings');
 await b.locator('#nav-messages').evaluate(e=>e.click());await b.waitForSelector('#account-dialog[open]');assert.equal(await b.locator('#account-dialog').getAttribute('data-social-view'),'messages');await b.click('#account-guest');assert.equal(await b.locator('#room').isVisible(),true);
 await a.fill('#youtube-input','https://youtu.be/dQw4w9WgXcQ');await a.click('#load-video');await a.getByRole('button',{name:'Play now',exact:true}).click();await b.waitForFunction(()=>window.fakeYT?.id==='dQw4w9WgXcQ');await a.locator('#watch-stage').hover();await a.click('#play');await b.waitForFunction(()=>fakeYT.state===1);
 await b.evaluate(()=>fakeYT.position-=2);await b.waitForTimeout(2100);let times=await Promise.all([a,b].map(p=>p.evaluate(()=>fakeYT.position)));assert(Math.abs(times[0]-times[1])<.5,JSON.stringify(times));
 const before=await b.evaluate(()=>{fakeYT.state=3;fakeYT.options.events.onStateChange({data:3});return fakeYT.seeks;});await b.waitForTimeout(2300);assert.equal(await b.evaluate(()=>fakeYT.seeks),before);await b.evaluate(()=>{fakeYT.state=1;fakeYT.options.events.onStateChange({data:1})});await b.waitForTimeout(1300);await b.locator('#resync').evaluate(e=>e.click());await b.waitForTimeout(300);times=await Promise.all([a,b].map(p=>p.evaluate(()=>fakeYT.position)));assert(Math.abs(times[0]-times[1])<.5);
 await a.screenshot({path:'/tmp/xparty-room-desktop.png',fullPage:true});await b.screenshot({path:'/tmp/xparty-room-mobile.png',fullPage:true});await a.locator('#mic').evaluate(e=>e.click());await b.locator('#mic').evaluate(e=>e.click());await a.waitForFunction(()=>document.querySelectorAll('.media-status .icon-control:not(.off)').length>=2,{},{timeout:15000});let mediaConnected=true;try{await a.waitForFunction(()=>__pcs.some(pc=>pc.connectionState==='connected'),{},{timeout:7000});console.log('PASS two-browser WebRTC fake-microphone connection');}catch(e){const diagnostics=await Promise.all([a,b].map(p=>p.evaluate(()=>__pcs.map(pc=>({state:pc.connectionState,ice:pc.iceConnectionState,signal:pc.signalingState,candidates:pc.__candidates.length,descriptions:!!pc.localDescription&&!!pc.remoteDescription})))));console.log('RTC diagnostics',JSON.stringify(diagnostics));if(process.env.XPARTY_REQUIRE_MEDIA==='1'||diagnostics.flat().some(pc=>pc.candidates>0||!pc.descriptions||pc.signal!=='stable'))throw e;mediaConnected=false;console.log('BLOCKED media transport: Chromium gathered zero ICE candidates in this environment; offer/answer negotiation completed.');}

 await a.locator('#retry-call').evaluate(e=>e.click());await a.waitForTimeout(1200);assert.equal(errors.length,0,errors.join('\n'));
 for(const width of[320,390,844,1366]){await a.setViewportSize({width,height:width===844?390:900});await a.locator('#theater').evaluate(e=>e.click());await a.waitForTimeout(100);assert.equal(await a.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+width);assert(await a.locator('#panel-chat').isVisible());assert.notEqual(await a.locator('#panel-chat').evaluate(e=>getComputedStyle(e).color),'rgba(0, 0, 0, 0)');await a.screenshot({path:'/tmp/xparty-release-'+width+'.png',fullPage:true});await a.locator('#theater').evaluate(e=>e.click());}
 assert.deepEqual(errors,[]);console.log('PASS room joining, saved names, crown/status, slider/theme, sound/display/language settings, separate friends chat, simulated YouTube drift/buffering/force-sync, manual call recovery and four viewport widths');
 }finally{await browser.close();await app.close()}
})().catch(e=>{console.error(e);process.exit(1)});
