const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright' : 'playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--allow-loopback-in-peer-connection','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream']});const errors=[];try{
const a=await browser.newPage({viewport:{width:1366,height:900}}),b=await browser.newPage({viewport:{width:390,height:844}});for(const p of[a,b])await p.addInitScript(()=>new MutationObserver(()=>{const c=document.querySelector('#agree-rules');if(c){c.checked=true;c.dispatchEvent(new Event('change'));document.querySelector('#agree-continue').click();}}).observe(document,{childList:true,subtree:true}));
for(const p of[a,b])await p.addInitScript(()=>localStorage.setItem('xparty-consent',JSON.stringify({essential:true,preferences:true,analytics:false})));
for(const p of[a,b]){p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8787/');}
await a.click('#create-toggle');await a.click('#create');await a.waitForSelector('#room:not([hidden])');const code=await a.locator('#room-code').innerText();assert.equal(code.length,7);await b.fill('#code',code);await b.waitForFunction(()=>!document.querySelector('#join-button').disabled);await b.click('#nickname-toggle');await b.fill('#join-nickname','Aanchal');await b.click('#join-button');await b.waitForSelector('#room:not([hidden])');await a.locator('.person-label>span').filter({hasText:'Aanchal'}).waitFor();console.log('PASS seven-character live availability and optional nickname');
await b.click('#panel-call');for(let i=0;i<3;i++){await a.fill('#message-input','Unread '+i);await a.locator('#chat-form button').click();}await b.waitForFunction(()=>document.querySelector('#panel-unread').textContent==='3');await b.click('#panel-chat');await b.locator('#messages').scrollIntoViewIfNeeded();await b.evaluate(()=>document.querySelector('#messages').dispatchEvent(new Event('scroll')));await a.waitForFunction(()=>[...document.querySelectorAll('.mine .read-receipt')].some(n=>n.getAttribute('aria-label').includes('Read by')));await b.click('#panel-both');console.log('PASS numbered message badge and view-based read receipt');
await a.click('#room-settings-button');await a.locator('#capacity-options button').getByText('4',{exact:true}).click();await a.check('#guest-themes');await a.selectOption('#room-theme','violet');await a.click('#save-room-settings');await b.waitForFunction(()=>document.documentElement.dataset.theme==='violet');await b.click('#room-settings-button');assert.equal(await b.locator('#room-theme').isEnabled(),true);await b.selectOption('#room-theme','ocean');await b.click('#save-room-settings');await a.waitForFunction(()=>document.documentElement.dataset.theme==='ocean');assert.equal(await a.locator('.topbar .brand-icon').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(216, 251, 140)');console.log('PASS host theme delegation, room settings Save and invariant brand');
await a.click('#nav-settings');await a.check('#notify-join');await a.selectOption('#language-select','hi');await a.click('#save-settings');await a.click('#nav-settings');assert.equal(await a.locator('#notify-join').isChecked(),true);await a.selectOption('#language-select','en');await a.click('#save-settings');console.log('PASS explicit settings save and notification preferences');
for(const p of[a,b]){await p.click('#theater');for(const mode of ['default','movie','call']){await p.selectOption('#theatre-view',mode);for(const viewport of p===a?[{width:1366,height:900}]:[{width:320,height:740},{width:390,height:844},{width:844,height:390}]){await p.setViewportSize(viewport);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'overflow '+mode+JSON.stringify(viewport));const buttons=await p.locator('.player-bar button,.topbar button,.room-tools summary').evaluateAll(es=>es.filter(e=>e.getClientRects().length).map(e=>({id:e.id,x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right})));assert.ok(buttons.every(x=>x.x>=-1&&x.right<=viewport.width+1),JSON.stringify(buttons));assert.equal(await p.locator('#room-code').isVisible(),true);}}await p.selectOption('#theatre-view','default');}
await b.setViewportSize({width:390,height:844});await b.screenshot({path:'/tmp/xparty-v5-mobile.png',fullPage:true});await a.screenshot({path:'/tmp/xparty-v5-desktop.png',fullPage:true});console.log('PASS responsive controls across three theatre modes and four viewport sizes');
await b.click('#exit-theatre');await b.locator('.brand').click();await b.waitForSelector('#lobby:not([hidden])');await b.click('#open-profile');assert.equal(await b.locator('#auth-method').isVisible(),true);assert.equal(await b.locator('#send-otp').isDisabled(),true);await b.click('#privacy-open');await b.getByRole('heading',{name:'Privacy & your data'}).waitFor();await b.locator('#privacy-dialog .close-dialog').click();await b.click('#account-guest');await b.click('#return-room');assert.equal(await b.locator('#room-code').textContent(),code);console.log('PASS logo home/return and honest account/phone setup state plus privacy notice');assert.deepEqual(errors,[]);console.log('PASS no unhandled browser errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1);});
